//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_MCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCC_Records_Push
    {
        public long R_Id { get; set; }
        public string Personnel_Id { get; set; }
        public string Store_Id { get; set; }
        public string Card_Id { get; set; }
        public string Valid_From { get; set; }
        public string Valid_To { get; set; }
        public string R_Type { get; set; }
        public string Status { get; set; }
        public Nullable<long> R_SAP_Id { get; set; }
        public string Full_Store { get; set; }
        public string Cessation { get; set; }
    }
}
