//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_MCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POS()
        {
            this.FTPs = new HashSet<FTP>();
        }
    
        public int POSID { get; set; }
        public string POSName { get; set; }
        public string POSIP { get; set; }
        public Nullable<int> POSPort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTP> FTPs { get; set; }
    }
}
