//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_MCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public long R_ID { get; set; }
        public Nullable<int> R_MCC_ID { get; set; }
        public Nullable<int> R_Year { get; set; }
        public Nullable<int> R_Month { get; set; }
        public Nullable<int> R_Day { get; set; }
        public Nullable<int> R_Hour { get; set; }
        public Nullable<int> R_Minute { get; set; }
        public Nullable<int> R_Second { get; set; }
        public string R_UserMaCC { get; set; }
    }
}
