//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_MCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_Push
    {
        public int R_ID { get; set; }
        public string Personnel_Id { get; set; }
        public string Store_Id { get; set; }
        public string Card_Id { get; set; }
        public string Valid_From { get; set; }
        public string Valid_To { get; set; }
        public string R_Type { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string DevicesID { get; set; }
        public string CESSATION { get; set; }
        public string Full_STORE { get; set; }
    }
}
