//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_MCC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FPT_TimeKeeperEntities : DbContext
    {
        public FPT_TimeKeeperEntities()
            : base("name=FPT_TimeKeeperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MCC_Records> MCC_Records { get; set; }
        public virtual DbSet<MCC_Records_Push> MCC_Records_Push { get; set; }
    }
}
