//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_MCC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int UsersID { get; set; }
        public string UsersName { get; set; }
        public Nullable<System.DateTime> UsersDayToWork { get; set; }
        public string UserCardNo { get; set; }
        public string UserPassword { get; set; }
        public string UserStatus { get; set; }
        public string UserDeviceID { get; set; }
    }
}
